#ifndef _H_R4_NAMES_REGISTRY
#define _H_R4_NAMES_REGISTRY

#if !defined( REGISTER_NAME )
#define REGISTER_NAME( name_ ) RED_DECLARE_NAME( name_ )
#define REGISTER_NAMED_NAME( varname_, string_ ) RED_DECLARE_NAMED_NAME( varname_, string_ )
#define REGISTER_NOT_REGISTERED
#endif

// <Swarm AI names >
REGISTER_NAME( HumbleCritterLair )
REGISTER_NAME( FlyingCritterLair )
REGISTER_NAME( speedMultiplier )
REGISTER_NAME( turnRatio )
REGISTER_NAME( individualRandomization )
REGISTER_NAME( actorsRangeDesired )
REGISTER_NAME( actorsRangeMax )
REGISTER_NAME( actorsGravity )
REGISTER_NAME( actorsBreakGravity )
REGISTER_NAME( fireRangeMin )
REGISTER_NAME( fireRangeMax )
REGISTER_NAME( fireRepultion )
REGISTER_NAME( mutualUndesiredDensity )
REGISTER_NAME( mutualRepultion )
REGISTER_NAME( hungerRatio )
REGISTER_NAME( eatingTime )
REGISTER_NAME( hungerGravity )
REGISTER_NAME( wanderGravity )
REGISTER_NAME( wallsDistance )
REGISTER_NAME( wallsRepulsion )
REGISTER_NAME( panicSpeedBoost )
REGISTER_NAME( panicActorsGravity )
REGISTER_NAME( actorRangeMultWhenPanic )
REGISTER_NAME( burnResistance )
REGISTER_NAME( postPanicDeathChance )
REGISTER_NAME( attackRange )
REGISTER_NAME( hasAttackBehaviour )
REGISTER_NAME( testLocation_hack )
REGISTER_NAME( walkSideway )
REGISTER_NAME( Strafing )
REGISTER_NAME( DesiredTargetYawDifference )
REGISTER_NAME( boidAnim )
REGISTER_NAME( wanderTime )
REGISTER_NAME( MovingIdleTarget )
REGISTER_NAME( staticFlyTarget )
REGISTER_NAME( groupStates )
REGISTER_NAME( ignorePoiAfterReach )
REGISTER_NAME( maxVelocity )
REGISTER_NAME( tooCloseMultiplier )
REGISTER_NAME( tooFarMultiplier )
REGISTER_NAME( randomDirMultiplier )
REGISTER_NAME( thinnessMultiplier )
REGISTER_NAME( collisionMultiplier )
REGISTER_NAME( randomNeighboursRatio )
REGISTER_NAME( neighbourCount )
REGISTER_NAME( minDistToGround )
REGISTER_NAME( velocityVariation )
REGISTER_NAME( tooCloseVariation )
REGISTER_NAME( tooFarVariation )
REGISTER_NAME( genericVariation )
REGISTER_NAME( confortableDistBetweenGroups )
REGISTER_NAME( livesUnderWater )
REGISTER_NAME( waterSurfaceCollisionForce )
REGISTER_NAME( lowFlyTarget )
REGISTER_NAME( randomDirRatio )
REGISTER_NAME( groupState )
REGISTER_NAME( closestOnly )
REGISTER_NAME( stateID )
REGISTER_NAME( frictionMultiplier )
REGISTER_NAME( minVelocity )
REGISTER_NAME( cozyFlyDist )
REGISTER_NAME( skyHeight )
REGISTER_NAME( OnBoidPointOfInterestReached )
REGISTER_NAME( OnActivated )
REGISTER_NAME( OnDeactivated )
REGISTER_NAME( glidingPercentage )
REGISTER_NAME( groupState_name )
REGISTER_NAME( x )
REGISTER_NAME( y )
REGISTER_NAME( z )
// <Swarm AI names />

// < behTree >
REGISTER_NAME( ConditionIsDead )
REGISTER_NAME( OnRevive )
REGISTER_NAME( ConditionIsEnemyAround )
REGISTER_NAME( ConditionAttackersCount )
REGISTER_NAME( ConditionIsTargetThePlayer )
REGISTER_NAME( ConditionIsInInterior )
REGISTER_NAME( ConditionAmIInInterior )
REGISTER_NAME( ConditionIsPlayerInInterior )
REGISTER_NAME( ConditionalAmIOrAPInInterior )
REGISTER_NAME( IgnoreInteriorsDuringPathfinding )
REGISTER_NAME( ChangeBehaviorGraph )
REGISTER_NAME( MetanodeDecorateOnCombatstyle )
REGISTER_NAME( HasAbility )
REGISTER_NAME( SetBehaviorVariable )
REGISTER_NAME( DisableTalkInteraction )
REGISTER_NAME( DismountCheck )
REGISTER_NAME( OverrideBehaviorVariable )
REGISTER_NAME( CalculateTicketImportance )
REGISTER_NAME( CombatTargetSelectionBase )
REGISTER_NAME( CombatTargetSelection )
REGISTER_NAME( ClosestNonFriendlyTargetSelection )
REGISTER_NAME( ForceTarget )
REGISTER_NAME( UnforceTarget )
REGISTER_NAME( ReevaluateCombatTarget )
REGISTER_NAME( RequestItems )
REGISTER_NAME( riderIdleTree )
REGISTER_NAME( RiderIdleRootDynamic )
REGISTER_NAME( Rider_WaitHorseScriptedAction )
REGISTER_NAME( RiderPairingLogic )
REGISTER_NAME( RiderPairWithHorse )
REGISTER_NAME( HorsePairWithRider )
REGISTER_NAME( CluePathData )
REGISTER_NAME( CluePathDecorator )
REGISTER_NAME( FollowPredefinedPathRuberBand )
REGISTER_NAME( HorseSpeedManager )
REGISTER_NAME( SelectTargetOrMountByTagDecorator )
REGISTER_NAME( HighLevelOffense )
REGISTER_NAME( HighLevelCombatBase )
REGISTER_NAME( HighLevelCombat )
REGISTER_NAME( HighLevelAnimalCombat )
REGISTER_NAME( HighLevelDangerBase )
REGISTER_NAME( HighLevelDanger )
REGISTER_NAME( HighLevelDangerTamable )
REGISTER_NAME( HighLevelDangerWildHorse )
REGISTER_NAME( CustomBruxaDeathDecorator )
REGISTER_NAME( ProlongHLCombat )
REGISTER_NAME( CombatActivatedNotifier )
REGISTER_NAME( AtomicForgetCombatTarget )
REGISTER_NAME( SailorFollowPath )
REGISTER_NAME( SailorMoveToPath )
REGISTER_NAME( SailorMoveTo )
REGISTER_NAME( RiderPursueHorse )
REGISTER_NAME( RiderRotateToHorse )
REGISTER_NAME( RidingManager )
REGISTER_NAME( RidingCheck )
REGISTER_NAME( RiderForcedBehavior )
REGISTER_NAME( SendScaredEvent )
REGISTER_NAME( ReceiveScaredEvent )
REGISTER_NAME( SpeechCondition )
REGISTER_NAME( IsInChatScene )
REGISTER_NAME( IsSpeaking )
REGISTER_NAME( HasVoiceset )
REGISTER_NAME( Speech )
REGISTER_NAME( PlayVoiceset )
REGISTER_NAME( PlayVoicesetOnDeactivation )
REGISTER_NAME( PC_ReleaseControl )
REGISTER_NAME( PC_LockControl )
REGISTER_NAME( ShouldPursueTarget )
REGISTER_NAME( FlightIdleDynamic )
REGISTER_NAME( TicketDecorator )
REGISTER_NAME( TicketManager )
REGISTER_NAME( R4FollowPredefinedPathWithCompanion )
REGISTER_NAME( SetupCombatTargeting )
REGISTER_NAME( RainReactionEvent )
REGISTER_NAME( rain_shelter )
// < /behTree >

// < Saving flags for beh trees >
REGISTER_NAME( wasMountedWhenSaving )
REGISTER_NAME( vehicleSlot_save )
REGISTER_NAME( wasMountedOnBoatWhenSaving )
REGISTER_NAME( pairedBoat_save )
// < /Saving flags for beh trees >

// < ????? >
REGISTER_NAME( DynamicCombatStyle )
REGISTER_NAME( Flight )
REGISTER_NAME( FlyAround )
REGISTER_NAME( FlyAroundTarget )
REGISTER_NAME( FlyAroundPosition )
REGISTER_NAME( FlyTo )
REGISTER_NAME( FlyToTarget )
REGISTER_NAME( FlyToPosition )
REGISTER_NAME( FlightDecorator )
REGISTER_NAME( GlideDecorator )
REGISTER_NAME( FindLandingSpot )
REGISTER_NAME( LandingDecorator )
REGISTER_NAME( TakeOffDecorator )
REGISTER_NAME( TicketGet )
REGISTER_NAME( TicketHas )
REGISTER_NAME( TicketRequest )
REGISTER_NAME( TicketRelease )
REGISTER_NAME( TicketLock )
REGISTER_NAME( BroadcastReactionScene )
REGISTER_NAME( FlyYaw )
REGISTER_NAME( FlyPitch )
REGISTER_NAME( FlySpeed )
REGISTER_NAME( Fly2Glide )
REGISTER_NAME( CarriesOpenFire )
REGISTER_NAME( Igni )
REGISTER_NAME( Aard )
// < /????? >

// < carrying items >
REGISTER_NAME( CarryingItemManager )
REGISTER_NAME( FindSourceItemStore )
REGISTER_NAME( FindDestinationItemStore )
REGISTER_NAME( BaseCarryingItemNode )
REGISTER_NAME( PickCarryableItem )
REGISTER_NAME( DropCarryableItem )
REGISTER_NAME( BaseCarryingItemDecorator )
REGISTER_NAME( ConditionIsCarryingItem )
REGISTER_NAME( PickUpItem )
REGISTER_NAME( DropItem )
REGISTER_NAME( PickUpItemOverride )
REGISTER_NAME( DropItemOverride )
REGISTER_NAME( AttachItem )
REGISTER_NAME( DetachItem )
REGISTER_NAME( heldItemType )
// < / carrying items >

REGISTER_NAME( GreetingReactionScene )

// < events >
REGISTER_NAME( AI_Adjust )
REGISTER_NAME( AI_Land )
REGISTER_NAME( AI_TakeOff )
REGISTER_NAME( AI_Load_RiderIdleRoot )
REGISTER_NAME( AI_RequestCombatEvaluation )
REGISTER_NAME( AI_BecomeScared )
REGISTER_NAME( AI_StopBeingScared )
REGISTER_NAME( AI_Rider_Load_Forced )
REGISTER_NAME( AI_Rider_Forced_Cancel )
REGISTER_NAME( AI_ForceImmediateTicketImportanceUpdate )
REGISTER_NAME( PairHorse )
REGISTER_NAME( UnpairHorse )
REGISTER_NAME( HorseLost )
REGISTER_NAME( RidingManagerMountHorse )
REGISTER_NAME( RidingManagerDismountHorse )
REGISTER_NAME( RidingManagerMountBoat )
REGISTER_NAME( RidingManagerDismountBoat )
REGISTER_NAME( RiderHorseReachability )
REGISTER_NAME( HorseSummon )
REGISTER_NAME( HorseNeeded )
REGISTER_NAME( HorseMountEnd )
REGISTER_NAME( TICKET_ )
REGISTER_NAME( TICKET_Melee )
REGISTER_NAME( AI_Strafing_GetAngleDiff )
REGISTER_NAME( AI_Strafing_LockOrientation )
REGISTER_NAME( AI_Strafing_SetMovementSpeed )
REGISTER_NAME( AI_Strafing_FastSurround )
REGISTER_NAME( AI_LostTicket )
REGISTER_NAME( AI_DynamicCombatStyle )
REGISTER_NAME( RequestInstantDismount )
REGISTER_NAME( AI_NeutralIsDanger )
REGISTER_NAME( AI_Load_FlightIdle )
REGISTER_NAME( freeFlight )
REGISTER_NAME( CombatActivated )
// < events/ >

// AI storage
REGISTER_NAME( CombatLock )
REGISTER_NAME( FLIGHT_DATA )
REGISTER_NAME( RiderData )
REGISTER_NAME( HorseData )
REGISTER_NAME( AnimalData )
REGISTER_NAME( horse )
REGISTER_NAME( rider )
REGISTER_NAME( generic_horse )
REGISTER_NAME( CarryingItemData )
REGISTER_NAME( PLAYER_horse )
REGISTER_NAME( player_last_mounted_vehicle )


// < AI params >
REGISTER_NAME( targetOnlyPlayer )
REGISTER_NAME( hostileActorWeight )
REGISTER_NAME( currentTargetWeight )
REGISTER_NAME( rememberedHits )
REGISTER_NAME( hitterWeight )
REGISTER_NAME( maxWeightedDistance )
REGISTER_NAME( distanceWeight )
REGISTER_NAME( playerWeightProbability )
REGISTER_NAME( playerWeight )
REGISTER_NAME( monsterWeight )
REGISTER_NAME( skipVehicle )
REGISTER_NAME( skipVehicleProbability )
REGISTER_NAME( skipUnreachable )
REGISTER_NAME( skipUnreachableProbability )
REGISTER_NAME( skipNotThreatening )
REGISTER_NAME( skipNotThreateningProbability )
REGISTER_NAME( tag_horse_parking )
REGISTER_NAME( WildHorse )
// < AI params / >

/// custom
REGISTER_NAME( entries )
REGISTER_NAME( sets )
REGISTER_NAME( GetAITree )
REGISTER_NAME( UpdateLocomotion )
REGISTER_NAME( Finish )
REGISTER_NAME( k_pelvis_g )
REGISTER_NAME( Landing )

// <attitudegroups>
REGISTER_NAME( animals_peacefull )
REGISTER_NAME( animals_charmed )
REGISTER_NAME( npc_charmed )
// </attitudegroups>

// < steering graph flags >
REGISTER_NAME( RubberBandDistance )
REGISTER_NAME( HorseMoveType )
REGISTER_NAME( IsFollowingRoad )
// < /steering graph flags >

// < behaviour graph flags >
REGISTER_NAME( doBlendOnActivation )
// < /behaviour graph flags >

// r4Player
REGISTER_NAME( OnTeleported )
REGISTER_NAME( OnPlayerChanged )

// tutorial
REGISTER_NAME( OnGameStart )
REGISTER_NAME( OnGameEnd )
REGISTER_NAME( OnWorldStart )
REGISTER_NAME( OnWorldEnd )

// Gui
REGISTER_NAME( OnRefresh )
REGISTER_NAME( OnLoadingFailed )

// ScriptFunctions
REGISTER_NAME( MountVehicle )
REGISTER_NAME( MountHorse )
REGISTER_NAME( MountBoat )
REGISTER_NAME( GetGameplayVisibility )
REGISTER_NAME( CanBeTargeted )
REGISTER_NAME( ForceSelectLockTarget )
REGISTER_NAME( HardLockToTarget )
REGISTER_NAME( UnlockMissedAchievements )

// Behavior variables
REGISTER_NAME( isPerformingSpecialAttack )
REGISTER_NAME( combatActionType )
REGISTER_NAME( npcStance )

// new game +
REGISTER_NAME( NewGamePlus )


#if defined( REGISTER_NOT_REGISTERED )
#undef REGISTER_NAME
#undef REGISTER_NAMED_NAME
#undef REGISTER_NOT_REGISTERED
#endif

#endif // _H_R4_NAMES_REGISTRY
