
#pragma once

enum EDialogTimelineCommandId
{
	ID_ADD_PAUSE_AFTER = 4002,
	ID_ADD_PAUSE_BEFORE,
	ID_ADD_SCRIPT_LINE_BEFORE,
	ID_ADD_SCRIPT_LINE_AFTER,
	ID_ADD_BEHAVIOR_EVENT,
	ID_ADD_ANIMATION_EVENT,
	ID_ADD_CHANGE_ACTOR_GAME_STATE_EVENT,
	ID_ADD_ADDITIVE_ANIMATION_EVENT,
	ID_ADD_OVERRIDE_ANIMATION_EVENT,
	ID_ADD_EQUIP_ITEM_EVENT,
	ID_ADD_MORPH_EVENT,
	ID_ADD_D_PX_CLOTH_EVENT,
	ID_ADD_DANGLES_SHAKE_EVENT,
	ID_ADD_D_DANGLE_EVENT,
	ID_ADD_RESET_DANGLE_EVENT,
	ID_ADD_ACTOR_EFFECT_ITEM_EVENT,
	ID_ADD_PROP_EFFECT_ITEM_EVENT,
	ID_ADD_ACTOR_EFFECT_DURATION_ITEM_EVENT,
	ID_ADD_CURVE_ANIMATION_EVENT,
	ID_ADD_ENTER_ACTOR_EVENT,
	ID_ADD_EXIT_ACTOR_EVENT,
	ID_ADD_CAMERA_EVENT,
	ID_BLEND_CAMERA_EVENT_PLOT_POSITION,
	ID_BLEND_CAMERA_EVENT_PLOT_ROTATION,
	ID_REMOVE_FROM_CAMERA_BLEND,
	ID_ADD_ENHANCED_BLEND_INTERPOLATED_CAMERA_EVENT,
	ID_ADD_LOOKAT_EVENT,
	ID_ADD_LOOKAT_DURATION_EVENT,
	ID_ADD_LOOKAT_GAMEPLAY_EVENT,
	ID_ADD_VISIBILITY_EVENT,
	ID_ADD_APPEARANCE_EVENT,
	ID_ADD_HIRES_SHADOWS_EVENT,
	ID_ADD_MIMIC_LOD_EVENT,
	ID_ADD_PROP_VISIBILITY_EVENT,
	ID_ADD_FADE_EVENT,
	ID_ADD_WEATHER_EVENT,
	ID_ADD_ADDFACT_EVENT,
	ID_ADD_CAMERALIGHT_EVENT,
	ID_ADD_OPENDOOR_EVENT,
	ID_ADD_SURFACE_EFFECT_EVENT,
	ID_ADD_ATTACH_PROP_TO_BONE,
	ID_ADD_MUSIC_EVENT,
	ID_ADD_SOUND_EVENT,
	ID_ADD_HIT_SOUND_EVENT,
	ID_ADD_DIALOG_LINE_EVENT,
	//ID_ADD_ROTATE_TO_CAMERA_EVENT,
	ID_ADD_MIMICS_EVENT,
	ID_ADD_MIMICS_ANIMATION_EVENT,
	ID_ADD_CAMERA_ANIMATION_EVENT,
	ID_ADD_MIMICS_POSE_EVENT,
	ID_ADD_MIMICS_FILTER_EVENT,
	ID_ADD_CUSTOM_CAMERA_INSTANCE,
	ID_ADD_GAMEPLAY_CAMERA_EVENT,
	ID_ADD_START_BLEND_TO_GAMEPLAY_CAMERA_EVENT,
	ID_ADD_SCENE_PROP_PLACEMENT_EVENT,
	ID_ADD_WORLD_PROP_PLACEMENT_EVENT,
	ID_ADD_LIGHT_PROPERTIES_EVENT,
	ID_ADD_PLACEMENT_OVERRIDE_EVENT,
	ID_ADD_PLACEMENT_OVERRIDE_EVENT_DURATION,
	ID_ADD_PLACEMENT_OVERRIDE_BLEND_INTERPOLATED_EVENT,
	ID_ADD_PLACEMENT_OVERRIDE_BLEND,
	ID_ADD_PLACEMENT_WALK,
	ID_ADD_TO_CUSTOM_CAMERA_LIST,
	ID_DETACH_FROM_CUSTOM_CAMERA_LIST,
	ID_REMOVE_CAMERA_BLEND,
	ID_ADD_ENHANCED_CAMERA_BLEND,
	ID_ADD_TO_CAMERA_ENHANCED_BLEND,
	ID_REMOVE_FROM_CAMERA_ENHANCED_BLEND,
	ID_ADD_CHANGE_POSE,
	ID_ADD_PAUSE_5,
	ID_ADD_PAUSE_15,
	ID_ADD_PAUSE_30,
	ID_ALIGN_STARTS,
	ID_ALIGN_ENDS,
	ID_ALIGN_START_TO_END,
	ID_ALIGN_END_TO_SECTIONS_END,
	ID_GROUP_EVENTS,
	ID_UNGROUP_EVENTS,
	ID_LINK_EVENT,
	ID_UNLINK_EVENT,
	ID_MUTE_EVENT,
	ID_GOTO_MARKER,
	ID_OVERRIDE_PLACEMENT_COPY_TO_DIALOGSLOT,
	ID_LIGHT_COPY_TRANSFORM_FROM_DEF,
	ID_LIGHT_GO_TO_CENTER_SS,
	ID_NORMAL_EVENT,
	ID_MARK_EVENT,
	ID_LOCK_EVENT,
	ID_SET_AS_BACKGROUND_LINE,
	ID_SET_AS_NONBACKGROUND_LINE,
	ID_ADD_POSE_KEY_EVENT,
	ID_TOGGLE_TIME_PAUSE,
	ID_LIMIT_MIN_SET,
	ID_LIMIT_MAX_SET,
	ID_LIMIT_MIN_RESET,
	ID_LIMIT_MAX_RESET,
	ID_ARROW_LEFT,
	ID_ARROW_RIGHT,
	ID_ARROW_UP,
	ID_ARROW_DOWN,
	ID_CREATE_PLACEMENT_FOR_ANIM_PEVLIS,
	ID_SPLIT_ANIMATION_EVENT,
	ID_COPY_CAM_LIGHTS,
	ID_PASTE_CAM_LIGHTS,
	ID_TOGGLE_ENTITY_HELPER_IS_INTERACTIVE,

	ID_INTERPOLATION_EVENT_CREATE,
	ID_INTERPOLATION_EVENT_DESTROY,
	ID_INTERPOLATION_EVENT_ATTACH_KEY,
	ID_INTERPOLATION_EVENT_DETACH_KEY,
	ID_INTERPOLATION_EVENT_PLOT,

	ID_ADD_EVENT_LODOVERRIDE,

	ID_ADD_DEBUG_COMMENT_EVENT,
	ID_SET_CURRENT_TIME_ZERO,
	ID_SET_CURRENT_TIME_END,
	ID_ADD_GENERIC_EVENT // Do not add Ids after this one there might be dynamic ids 
};

/*
Function object for sorting timeline items by start time.
*/
class TimelineItemStartSorter
{
public:
	Bool operator()( const ITimelineItem* a, const ITimelineItem* b ) const
	{
		ASSERT( a && b );

		return !a ? true : !b ? false : a->GetStart() < b->GetStart();
	}
};

/*
Function object for sorting timeline items by end time.
*/
class TimelineItemEndSorter
{
public:
	Bool operator()( const ITimelineItem* a, const ITimelineItem* b ) const
	{
		ASSERT( a && b );

		return !a ? true : !b ? false : ( a->GetStart() + a->GetDuration() ) > ( b->GetStart() + b->GetDuration() );
	}
};
