/* This file was autogenerated. Do not edit! */
#ifndef _INCL_MOJOSHADER_VERSION_H_
#define _INCL_MOJOSHADER_VERSION_H_
#define MOJOSHADER_VERSION 1139
#define MOJOSHADER_CHANGESET "hg-1139:8cda6a463824"
#endif

