/**
* Copyright (c) 2015 CD Projekt Red. All Rights Reserved.
*/

#pragma once

/* This file is automatically generated during the build process. Do not edit */

const unsigned char SCRIPTS_HASH[32+1] = {'\0'};
