/**
* Copyright c 2012 CD Projekt Red. All Rights Reserved.
*/
#pragma once

enum SceneCompletionReason : CEnum::TValueType
{
	SCR_NONE,
	SCR_SCENE_ENDED,
	SCR_KILLED_BY_QUEST,
	SCR_WORLD_UNLOADING,
	SCR_ACTOR_KILLED,
	SCR_ACTOR_DESPAWN,
	SCR_ACTOR_STOLEN,
	SCR_ACTOR_REACTING,
	SCR_ACTOR_IN_COMBAT,
	SCR_DIED,
	SCR_TIMEDOUT,
	SCR_INTERRUPTED,
	SCR_INVALID_SCENE,
	SCR_PLAYER_DESTROYED,
	SCR_PLAYER_DETACHED,
	SCR_STOPPED,
	SCR_SYSTEM_RESET,
	SCR_CANNOT_START,
	SCR_MAX
};

BEGIN_ENUM_RTTI( SceneCompletionReason );
	ENUM_OPTION( SCR_NONE );
	ENUM_OPTION( SCR_SCENE_ENDED );
	ENUM_OPTION( SCR_KILLED_BY_QUEST );
	ENUM_OPTION( SCR_WORLD_UNLOADING );
	ENUM_OPTION( SCR_ACTOR_KILLED );
	ENUM_OPTION( SCR_ACTOR_DESPAWN );
	ENUM_OPTION( SCR_ACTOR_STOLEN );
	ENUM_OPTION( SCR_ACTOR_REACTING );
	ENUM_OPTION( SCR_ACTOR_IN_COMBAT );
	ENUM_OPTION( SCR_DIED );
	ENUM_OPTION( SCR_TIMEDOUT );
	ENUM_OPTION( SCR_INTERRUPTED );
	ENUM_OPTION( SCR_INVALID_SCENE );
	ENUM_OPTION( SCR_PLAYER_DESTROYED );
	ENUM_OPTION( SCR_STOPPED );
	ENUM_OPTION( SCR_SYSTEM_RESET );
	ENUM_OPTION( SCR_CANNOT_START );
	ENUM_OPTION( SCR_MAX );
END_ENUM_RTTI()