/* soapttsoapcgiProxy.h
   Generated by gSOAP 2.8.14 from ttsoapcgi.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapttsoapcgiProxy_H
#define soapttsoapcgiProxy_H
#include "soapH.h"

class SOAP_CMAC ttsoapcgiProxy : public soap
{ public:
	/// Endpoint URL of service 'ttsoapcgiProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	ttsoapcgiProxy();
	/// Construct from another engine state
	ttsoapcgiProxy(const struct soap&);
	/// Constructor with endpoint URL
	ttsoapcgiProxy(const char *url);
	/// Constructor with engine input+output mode control
	ttsoapcgiProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	ttsoapcgiProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	ttsoapcgiProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~ttsoapcgiProxy();
	/// Initializer used by constructors
	virtual	void ttsoapcgiProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'getDatabaseList' (returns error code or SOAP_OK)
	virtual	int getDatabaseList(struct ns1__getDatabaseListResponse &_param_1) { return this->getDatabaseList(NULL, NULL, _param_1); }
	virtual	int getDatabaseList(const char *endpoint, const char *soap_action, struct ns1__getDatabaseListResponse &_param_1);

	/// Web service operation 'getProjectList' (returns error code or SOAP_OK)
	virtual	int getProjectList(char *username, char *password, struct ns1__getProjectListResponse &_param_2) { return this->getProjectList(NULL, NULL, username, password, _param_2); }
	virtual	int getProjectList(const char *endpoint, const char *soap_action, char *username, char *password, struct ns1__getProjectListResponse &_param_2);

	/// Web service operation 'getProjectDataOptionList' (returns error code or SOAP_OK)
	virtual	int getProjectDataOptionList(struct ns1__getProjectDataOptionListResponse &_param_3) { return this->getProjectDataOptionList(NULL, NULL, _param_3); }
	virtual	int getProjectDataOptionList(const char *endpoint, const char *soap_action, struct ns1__getProjectDataOptionListResponse &_param_3);

	/// Web service operation 'DatabaseLogon' (returns error code or SOAP_OK)
	virtual	int DatabaseLogon(char *dbname, char *username, char *password, LONG64 &Cookie) { return this->DatabaseLogon(NULL, NULL, dbname, username, password, Cookie); }
	virtual	int DatabaseLogon(const char *endpoint, const char *soap_action, char *dbname, char *username, char *password, LONG64 &Cookie);

	/// Web service operation 'ProjectLogon' (returns error code or SOAP_OK)
	virtual	int ProjectLogon(ns1__CProject *pProj, char *username, char *password, LONG64 &Cookie) { return this->ProjectLogon(NULL, NULL, pProj, username, password, Cookie); }
	virtual	int ProjectLogon(const char *endpoint, const char *soap_action, ns1__CProject *pProj, char *username, char *password, LONG64 &Cookie);

	/// Web service operation 'DatabaseLogoff' (returns error code or SOAP_OK)
	virtual	int DatabaseLogoff(LONG64 cookie, int &result) { return this->DatabaseLogoff(NULL, NULL, cookie, result); }
	virtual	int DatabaseLogoff(const char *endpoint, const char *soap_action, LONG64 cookie, int &result);

	/// Web service operation 'formattedTextSupport' (returns error code or SOAP_OK)
	virtual	int formattedTextSupport(LONG64 cookie, bool enableFormattedText, bool &formattingEnabled) { return this->formattedTextSupport(NULL, NULL, cookie, enableFormattedText, formattingEnabled); }
	virtual	int formattedTextSupport(const char *endpoint, const char *soap_action, LONG64 cookie, bool enableFormattedText, bool &formattingEnabled);

	/// Web service operation 'getTableList' (returns error code or SOAP_OK)
	virtual	int getTableList(LONG64 cookie, struct ns1__getTableListResponse &_param_4) { return this->getTableList(NULL, NULL, cookie, _param_4); }
	virtual	int getTableList(const char *endpoint, const char *soap_action, LONG64 cookie, struct ns1__getTableListResponse &_param_4);

	/// Web service operation 'getDropdownFieldForTable' (returns error code or SOAP_OK)
	virtual	int getDropdownFieldForTable(LONG64 cookie, char *tablename, struct ns1__getDropdownFieldForTableResponse &_param_5) { return this->getDropdownFieldForTable(NULL, NULL, cookie, tablename, _param_5); }
	virtual	int getDropdownFieldForTable(const char *endpoint, const char *soap_action, LONG64 cookie, char *tablename, struct ns1__getDropdownFieldForTableResponse &_param_5);

	/// Web service operation 'getDropdownFieldValuesForTable' (returns error code or SOAP_OK)
	virtual	int getDropdownFieldValuesForTable(LONG64 cookie, char *tablename, char *fieldname, struct ns1__getDropdownFieldValuesForTableResponse &_param_6) { return this->getDropdownFieldValuesForTable(NULL, NULL, cookie, tablename, fieldname, _param_6); }
	virtual	int getDropdownFieldValuesForTable(const char *endpoint, const char *soap_action, LONG64 cookie, char *tablename, char *fieldname, struct ns1__getDropdownFieldValuesForTableResponse &_param_6);

	/// Web service operation 'addDropdownFieldValuesForTable' (returns error code or SOAP_OK)
	virtual	int addDropdownFieldValuesForTable(LONG64 cookie, char *tablename, char *fieldname, ArrayOfCFieldValue *pValueList, int &result) { return this->addDropdownFieldValuesForTable(NULL, NULL, cookie, tablename, fieldname, pValueList, result); }
	virtual	int addDropdownFieldValuesForTable(const char *endpoint, const char *soap_action, LONG64 cookie, char *tablename, char *fieldname, ArrayOfCFieldValue *pValueList, int &result);

	/// Web service operation 'GetLinkDefinitionValues' (returns error code or SOAP_OK)
	virtual	int GetLinkDefinitionValues(LONG64 cookie, struct ns1__GetLinkDefinitionValuesResponse &_param_7) { return this->GetLinkDefinitionValues(NULL, NULL, cookie, _param_7); }
	virtual	int GetLinkDefinitionValues(const char *endpoint, const char *soap_action, LONG64 cookie, struct ns1__GetLinkDefinitionValuesResponse &_param_7);

	/// Web service operation 'getColumnsForTable' (returns error code or SOAP_OK)
	virtual	int getColumnsForTable(LONG64 cookie, char *tablename, struct ns1__getColumnsForTableResponse &_param_8) { return this->getColumnsForTable(NULL, NULL, cookie, tablename, _param_8); }
	virtual	int getColumnsForTable(const char *endpoint, const char *soap_action, LONG64 cookie, char *tablename, struct ns1__getColumnsForTableResponse &_param_8);

	/// Web service operation 'getFilterList' (returns error code or SOAP_OK)
	virtual	int getFilterList(LONG64 cookie, struct ns1__getFilterListResponse &_param_9) { return this->getFilterList(NULL, NULL, cookie, _param_9); }
	virtual	int getFilterList(const char *endpoint, const char *soap_action, LONG64 cookie, struct ns1__getFilterListResponse &_param_9);

	/// Web service operation 'getFilterListForTable' (returns error code or SOAP_OK)
	virtual	int getFilterListForTable(LONG64 cookie, char *tablename, struct ns1__getFilterListForTableResponse &_param_10) { return this->getFilterListForTable(NULL, NULL, cookie, tablename, _param_10); }
	virtual	int getFilterListForTable(const char *endpoint, const char *soap_action, LONG64 cookie, char *tablename, struct ns1__getFilterListForTableResponse &_param_10);

	/// Web service operation 'getRecordListForTable' (returns error code or SOAP_OK)
	virtual	int getRecordListForTable(LONG64 cookie, char *tablename, char *filtername, ArrayOfCTableColumn *columnlist, struct ns1__getRecordListForTableResponse &_param_11) { return this->getRecordListForTable(NULL, NULL, cookie, tablename, filtername, columnlist, _param_11); }
	virtual	int getRecordListForTable(const char *endpoint, const char *soap_action, LONG64 cookie, char *tablename, char *filtername, ArrayOfCTableColumn *columnlist, struct ns1__getRecordListForTableResponse &_param_11);

	/// Web service operation 'getTestConfig' (returns error code or SOAP_OK)
	virtual	int getTestConfig(LONG64 cookie, char *name, struct ns1__getTestConfigResponse &_param_12) { return this->getTestConfig(NULL, NULL, cookie, name, _param_12); }
	virtual	int getTestConfig(const char *endpoint, const char *soap_action, LONG64 cookie, char *name, struct ns1__getTestConfigResponse &_param_12);

	/// Web service operation 'getTestConfigByRecordID' (returns error code or SOAP_OK)
	virtual	int getTestConfigByRecordID(LONG64 cookie, LONG64 recordID, struct ns1__getTestConfigByRecordIDResponse &_param_13) { return this->getTestConfigByRecordID(NULL, NULL, cookie, recordID, _param_13); }
	virtual	int getTestConfigByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, struct ns1__getTestConfigByRecordIDResponse &_param_13);

	/// Web service operation 'addTestConfig' (returns error code or SOAP_OK)
	virtual	int addTestConfig(LONG64 cookie, ns1__CSystem *pTestConfig, LONG64 &recordID) { return this->addTestConfig(NULL, NULL, cookie, pTestConfig, recordID); }
	virtual	int addTestConfig(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CSystem *pTestConfig, LONG64 &recordID);

	/// Web service operation 'editTestConfig' (returns error code or SOAP_OK)
	virtual	int editTestConfig(LONG64 cookie, char *name, struct ns1__editTestConfigResponse &_param_14) { return this->editTestConfig(NULL, NULL, cookie, name, _param_14); }
	virtual	int editTestConfig(const char *endpoint, const char *soap_action, LONG64 cookie, char *name, struct ns1__editTestConfigResponse &_param_14);

	/// Web service operation 'editTestConfigByRecordID' (returns error code or SOAP_OK)
	virtual	int editTestConfigByRecordID(LONG64 cookie, LONG64 recordID, struct ns1__editTestConfigByRecordIDResponse &_param_15) { return this->editTestConfigByRecordID(NULL, NULL, cookie, recordID, _param_15); }
	virtual	int editTestConfigByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, struct ns1__editTestConfigByRecordIDResponse &_param_15);

	/// Web service operation 'saveTestConfig' (returns error code or SOAP_OK)
	virtual	int saveTestConfig(LONG64 cookie, ns1__CSystem *pTestConfig, int &result) { return this->saveTestConfig(NULL, NULL, cookie, pTestConfig, result); }
	virtual	int saveTestConfig(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CSystem *pTestConfig, int &result);

	/// Web service operation 'deleteTestConfig' (returns error code or SOAP_OK)
	virtual	int deleteTestConfig(LONG64 cookie, char *name, int &result) { return this->deleteTestConfig(NULL, NULL, cookie, name, result); }
	virtual	int deleteTestConfig(const char *endpoint, const char *soap_action, LONG64 cookie, char *name, int &result);

	/// Web service operation 'deleteTestConfigByRecordID' (returns error code or SOAP_OK)
	virtual	int deleteTestConfigByRecordID(LONG64 cookie, LONG64 recordID, int &result) { return this->deleteTestConfigByRecordID(NULL, NULL, cookie, recordID, result); }
	virtual	int deleteTestConfigByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'cancelSaveTestConfig' (returns error code or SOAP_OK)
	virtual	int cancelSaveTestConfig(LONG64 cookie, LONG64 recordID, int &result) { return this->cancelSaveTestConfig(NULL, NULL, cookie, recordID, result); }
	virtual	int cancelSaveTestConfig(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'getAttachmentTypes' (returns error code or SOAP_OK)
	virtual	int getAttachmentTypes(LONG64 cookie, struct ns1__getAttachmentTypesResponse &_param_16) { return this->getAttachmentTypes(NULL, NULL, cookie, _param_16); }
	virtual	int getAttachmentTypes(const char *endpoint, const char *soap_action, LONG64 cookie, struct ns1__getAttachmentTypesResponse &_param_16);

	/// Web service operation 'getReportRunResultsByName' (returns error code or SOAP_OK)
	virtual	int getReportRunResultsByName(LONG64 cookie, char *name, struct ns1__getReportRunResultsByNameResponse &_param_17) { return this->getReportRunResultsByName(NULL, NULL, cookie, name, _param_17); }
	virtual	int getReportRunResultsByName(const char *endpoint, const char *soap_action, LONG64 cookie, char *name, struct ns1__getReportRunResultsByNameResponse &_param_17);

	/// Web service operation 'getReportRunResultsByRecordID' (returns error code or SOAP_OK)
	virtual	int getReportRunResultsByRecordID(LONG64 cookie, LONG64 recordID, struct ns1__getReportRunResultsByRecordIDResponse &_param_18) { return this->getReportRunResultsByRecordID(NULL, NULL, cookie, recordID, _param_18); }
	virtual	int getReportRunResultsByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, struct ns1__getReportRunResultsByRecordIDResponse &_param_18);

	/// Web service operation 'getEventDefinitionList' (returns error code or SOAP_OK)
	virtual	int getEventDefinitionList(LONG64 cookie, char *tablename, struct ns1__getEventDefinitionListResponse &_param_19) { return this->getEventDefinitionList(NULL, NULL, cookie, tablename, _param_19); }
	virtual	int getEventDefinitionList(const char *endpoint, const char *soap_action, LONG64 cookie, char *tablename, struct ns1__getEventDefinitionListResponse &_param_19);

	/// Web service operation 'getDefectEventDefinitionList' (returns error code or SOAP_OK)
	virtual	int getDefectEventDefinitionList(LONG64 cookie, struct ns1__getDefectEventDefinitionListResponse &_param_20) { return this->getDefectEventDefinitionList(NULL, NULL, cookie, _param_20); }
	virtual	int getDefectEventDefinitionList(const char *endpoint, const char *soap_action, LONG64 cookie, struct ns1__getDefectEventDefinitionListResponse &_param_20);

	/// Web service operation 'getCustomFieldsDefinitionList' (returns error code or SOAP_OK)
	virtual	int getCustomFieldsDefinitionList(LONG64 cookie, char *tablename, struct ns1__getCustomFieldsDefinitionListResponse &_param_21) { return this->getCustomFieldsDefinitionList(NULL, NULL, cookie, tablename, _param_21); }
	virtual	int getCustomFieldsDefinitionList(const char *endpoint, const char *soap_action, LONG64 cookie, char *tablename, struct ns1__getCustomFieldsDefinitionListResponse &_param_21);

	/// Web service operation 'getDefectCustomFieldsDefinitionList' (returns error code or SOAP_OK)
	virtual	int getDefectCustomFieldsDefinitionList(LONG64 cookie, struct ns1__getDefectCustomFieldsDefinitionListResponse &_param_22) { return this->getDefectCustomFieldsDefinitionList(NULL, NULL, cookie, _param_22); }
	virtual	int getDefectCustomFieldsDefinitionList(const char *endpoint, const char *soap_action, LONG64 cookie, struct ns1__getDefectCustomFieldsDefinitionListResponse &_param_22);

	/// Web service operation 'getDefect' (returns error code or SOAP_OK)
	virtual	int getDefect(LONG64 cookie, LONG64 defectNumber, char *summary, bool bDownloadAttachments, struct ns1__getDefectResponse &_param_23) { return this->getDefect(NULL, NULL, cookie, defectNumber, summary, bDownloadAttachments, _param_23); }
	virtual	int getDefect(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 defectNumber, char *summary, bool bDownloadAttachments, struct ns1__getDefectResponse &_param_23);

	/// Web service operation 'getDefectByRecordID' (returns error code or SOAP_OK)
	virtual	int getDefectByRecordID(LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__getDefectByRecordIDResponse &_param_24) { return this->getDefectByRecordID(NULL, NULL, cookie, recordID, bDownloadAttachments, _param_24); }
	virtual	int getDefectByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__getDefectByRecordIDResponse &_param_24);

	/// Web service operation 'addDefect' (returns error code or SOAP_OK)
	virtual	int addDefect(LONG64 cookie, ns1__CDefect *pDefect, LONG64 &recordID) { return this->addDefect(NULL, NULL, cookie, pDefect, recordID); }
	virtual	int addDefect(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CDefect *pDefect, LONG64 &recordID);

	/// Web service operation 'addDefectWithLink' (returns error code or SOAP_OK)
	virtual	int addDefectWithLink(LONG64 cookie, ns1__CDefect *pDefect, LONG64 testRunRecordID, LONG64 &recordID) { return this->addDefectWithLink(NULL, NULL, cookie, pDefect, testRunRecordID, recordID); }
	virtual	int addDefectWithLink(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CDefect *pDefect, LONG64 testRunRecordID, LONG64 &recordID);

	/// Web service operation 'deleteDefect' (returns error code or SOAP_OK)
	virtual	int deleteDefect(LONG64 cookie, LONG64 defectNumber, char *summary, int &result) { return this->deleteDefect(NULL, NULL, cookie, defectNumber, summary, result); }
	virtual	int deleteDefect(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 defectNumber, char *summary, int &result);

	/// Web service operation 'deleteDefectByRecordID' (returns error code or SOAP_OK)
	virtual	int deleteDefectByRecordID(LONG64 cookie, LONG64 recordID, int &result) { return this->deleteDefectByRecordID(NULL, NULL, cookie, recordID, result); }
	virtual	int deleteDefectByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'editDefect' (returns error code or SOAP_OK)
	virtual	int editDefect(LONG64 cookie, LONG64 defectNumber, char *summary, bool bDownloadAttachments, struct ns1__editDefectResponse &_param_25) { return this->editDefect(NULL, NULL, cookie, defectNumber, summary, bDownloadAttachments, _param_25); }
	virtual	int editDefect(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 defectNumber, char *summary, bool bDownloadAttachments, struct ns1__editDefectResponse &_param_25);

	/// Web service operation 'editDefectByRecordID' (returns error code or SOAP_OK)
	virtual	int editDefectByRecordID(LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__editDefectByRecordIDResponse &_param_26) { return this->editDefectByRecordID(NULL, NULL, cookie, recordID, bDownloadAttachments, _param_26); }
	virtual	int editDefectByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__editDefectByRecordIDResponse &_param_26);

	/// Web service operation 'saveDefect' (returns error code or SOAP_OK)
	virtual	int saveDefect(LONG64 cookie, ns1__CDefect *pDefect, int &result) { return this->saveDefect(NULL, NULL, cookie, pDefect, result); }
	virtual	int saveDefect(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CDefect *pDefect, int &result);

	/// Web service operation 'cancelSaveDefect' (returns error code or SOAP_OK)
	virtual	int cancelSaveDefect(LONG64 cookie, LONG64 recordID, int &result) { return this->cancelSaveDefect(NULL, NULL, cookie, recordID, result); }
	virtual	int cancelSaveDefect(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'getAttachment' (returns error code or SOAP_OK)
	virtual	int getAttachment(LONG64 cookie, char *tablename, LONG64 recordID, LONG64 eventID, char *pszArchiveName, struct ns1__getAttachmentResponse &_param_27) { return this->getAttachment(NULL, NULL, cookie, tablename, recordID, eventID, pszArchiveName, _param_27); }
	virtual	int getAttachment(const char *endpoint, const char *soap_action, LONG64 cookie, char *tablename, LONG64 recordID, LONG64 eventID, char *pszArchiveName, struct ns1__getAttachmentResponse &_param_27);

	/// Web service operation 'getDefectAttachment' (returns error code or SOAP_OK)
	virtual	int getDefectAttachment(LONG64 cookie, char *pszArchiveName, struct ns1__getDefectAttachmentResponse &_param_28) { return this->getDefectAttachment(NULL, NULL, cookie, pszArchiveName, _param_28); }
	virtual	int getDefectAttachment(const char *endpoint, const char *soap_action, LONG64 cookie, char *pszArchiveName, struct ns1__getDefectAttachmentResponse &_param_28);

	/// Web service operation 'getTask' (returns error code or SOAP_OK)
	virtual	int getTask(LONG64 cookie, char *summary, struct ns1__getTaskResponse &_param_29) { return this->getTask(NULL, NULL, cookie, summary, _param_29); }
	virtual	int getTask(const char *endpoint, const char *soap_action, LONG64 cookie, char *summary, struct ns1__getTaskResponse &_param_29);

	/// Web service operation 'getTaskByRecordID' (returns error code or SOAP_OK)
	virtual	int getTaskByRecordID(LONG64 cookie, LONG64 recordID, struct ns1__getTaskByRecordIDResponse &_param_30) { return this->getTaskByRecordID(NULL, NULL, cookie, recordID, _param_30); }
	virtual	int getTaskByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, struct ns1__getTaskByRecordIDResponse &_param_30);

	/// Web service operation 'addTask' (returns error code or SOAP_OK)
	virtual	int addTask(LONG64 cookie, ns1__CTask *pTask, LONG64 &recordID) { return this->addTask(NULL, NULL, cookie, pTask, recordID); }
	virtual	int addTask(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CTask *pTask, LONG64 &recordID);

	/// Web service operation 'deleteTask' (returns error code or SOAP_OK)
	virtual	int deleteTask(LONG64 cookie, char *summary, int &result) { return this->deleteTask(NULL, NULL, cookie, summary, result); }
	virtual	int deleteTask(const char *endpoint, const char *soap_action, LONG64 cookie, char *summary, int &result);

	/// Web service operation 'deleteTaskByRecordID' (returns error code or SOAP_OK)
	virtual	int deleteTaskByRecordID(LONG64 cookie, LONG64 recordID, int &result) { return this->deleteTaskByRecordID(NULL, NULL, cookie, recordID, result); }
	virtual	int deleteTaskByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'editTask' (returns error code or SOAP_OK)
	virtual	int editTask(LONG64 cookie, char *summary, struct ns1__editTaskResponse &_param_31) { return this->editTask(NULL, NULL, cookie, summary, _param_31); }
	virtual	int editTask(const char *endpoint, const char *soap_action, LONG64 cookie, char *summary, struct ns1__editTaskResponse &_param_31);

	/// Web service operation 'editTaskByRecordID' (returns error code or SOAP_OK)
	virtual	int editTaskByRecordID(LONG64 cookie, LONG64 recordID, struct ns1__editTaskByRecordIDResponse &_param_32) { return this->editTaskByRecordID(NULL, NULL, cookie, recordID, _param_32); }
	virtual	int editTaskByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, struct ns1__editTaskByRecordIDResponse &_param_32);

	/// Web service operation 'saveTask' (returns error code or SOAP_OK)
	virtual	int saveTask(LONG64 cookie, ns1__CTask *pTask, int &result) { return this->saveTask(NULL, NULL, cookie, pTask, result); }
	virtual	int saveTask(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CTask *pTask, int &result);

	/// Web service operation 'cancelSaveTask' (returns error code or SOAP_OK)
	virtual	int cancelSaveTask(LONG64 cookie, LONG64 recordID, int &result) { return this->cancelSaveTask(NULL, NULL, cookie, recordID, result); }
	virtual	int cancelSaveTask(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'getGlobalUserList' (returns error code or SOAP_OK)
	virtual	int getGlobalUserList(LONG64 cookie, struct ns1__getGlobalUserListResponse &_param_33) { return this->getGlobalUserList(NULL, NULL, cookie, _param_33); }
	virtual	int getGlobalUserList(const char *endpoint, const char *soap_action, LONG64 cookie, struct ns1__getGlobalUserListResponse &_param_33);

	/// Web service operation 'getGlobalCustomerList' (returns error code or SOAP_OK)
	virtual	int getGlobalCustomerList(LONG64 cookie, struct ns1__getGlobalCustomerListResponse &_param_34) { return this->getGlobalCustomerList(NULL, NULL, cookie, _param_34); }
	virtual	int getGlobalCustomerList(const char *endpoint, const char *soap_action, LONG64 cookie, struct ns1__getGlobalCustomerListResponse &_param_34);

	/// Web service operation 'getUserLicenseList' (returns error code or SOAP_OK)
	virtual	int getUserLicenseList(LONG64 cookie, struct ns1__getUserLicenseListResponse &_param_35) { return this->getUserLicenseList(NULL, NULL, cookie, _param_35); }
	virtual	int getUserLicenseList(const char *endpoint, const char *soap_action, LONG64 cookie, struct ns1__getUserLicenseListResponse &_param_35);

	/// Web service operation 'getUser' (returns error code or SOAP_OK)
	virtual	int getUser(LONG64 cookie, char *firstName, char *middleInitials, char *lastName, struct ns1__getUserResponse &_param_36) { return this->getUser(NULL, NULL, cookie, firstName, middleInitials, lastName, _param_36); }
	virtual	int getUser(const char *endpoint, const char *soap_action, LONG64 cookie, char *firstName, char *middleInitials, char *lastName, struct ns1__getUserResponse &_param_36);

	/// Web service operation 'getUserByRecordID' (returns error code or SOAP_OK)
	virtual	int getUserByRecordID(LONG64 cookie, LONG64 recordID, struct ns1__getUserByRecordIDResponse &_param_37) { return this->getUserByRecordID(NULL, NULL, cookie, recordID, _param_37); }
	virtual	int getUserByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, struct ns1__getUserByRecordIDResponse &_param_37);

	/// Web service operation 'getUserForCurrentSession' (returns error code or SOAP_OK)
	virtual	int getUserForCurrentSession(LONG64 cookie, struct ns1__getUserForCurrentSessionResponse &_param_38) { return this->getUserForCurrentSession(NULL, NULL, cookie, _param_38); }
	virtual	int getUserForCurrentSession(const char *endpoint, const char *soap_action, LONG64 cookie, struct ns1__getUserForCurrentSessionResponse &_param_38);

	/// Web service operation 'addUser' (returns error code or SOAP_OK)
	virtual	int addUser(LONG64 cookie, ns1__CUser *pUser, LONG64 &recordID) { return this->addUser(NULL, NULL, cookie, pUser, recordID); }
	virtual	int addUser(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CUser *pUser, LONG64 &recordID);

	/// Web service operation 'editUser' (returns error code or SOAP_OK)
	virtual	int editUser(LONG64 cookie, char *firstName, char *middleInitials, char *lastName, struct ns1__editUserResponse &_param_39) { return this->editUser(NULL, NULL, cookie, firstName, middleInitials, lastName, _param_39); }
	virtual	int editUser(const char *endpoint, const char *soap_action, LONG64 cookie, char *firstName, char *middleInitials, char *lastName, struct ns1__editUserResponse &_param_39);

	/// Web service operation 'editUserByRecordID' (returns error code or SOAP_OK)
	virtual	int editUserByRecordID(LONG64 cookie, LONG64 recordID, struct ns1__editUserByRecordIDResponse &_param_40) { return this->editUserByRecordID(NULL, NULL, cookie, recordID, _param_40); }
	virtual	int editUserByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, struct ns1__editUserByRecordIDResponse &_param_40);

	/// Web service operation 'saveUser' (returns error code or SOAP_OK)
	virtual	int saveUser(LONG64 cookie, char *firstName, char *middleInitials, char *lastName, ns1__CUser *pUser, int &result) { return this->saveUser(NULL, NULL, cookie, firstName, middleInitials, lastName, pUser, result); }
	virtual	int saveUser(const char *endpoint, const char *soap_action, LONG64 cookie, char *firstName, char *middleInitials, char *lastName, ns1__CUser *pUser, int &result);

	/// Web service operation 'deleteUser' (returns error code or SOAP_OK)
	virtual	int deleteUser(LONG64 cookie, char *firstName, char *middleInitials, char *lastName, int &result) { return this->deleteUser(NULL, NULL, cookie, firstName, middleInitials, lastName, result); }
	virtual	int deleteUser(const char *endpoint, const char *soap_action, LONG64 cookie, char *firstName, char *middleInitials, char *lastName, int &result);

	/// Web service operation 'deleteUserByRecordID' (returns error code or SOAP_OK)
	virtual	int deleteUserByRecordID(LONG64 cookie, LONG64 recordID, int &result) { return this->deleteUserByRecordID(NULL, NULL, cookie, recordID, result); }
	virtual	int deleteUserByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'cancelSaveUser' (returns error code or SOAP_OK)
	virtual	int cancelSaveUser(LONG64 cookie, LONG64 recordID, int &result) { return this->cancelSaveUser(NULL, NULL, cookie, recordID, result); }
	virtual	int cancelSaveUser(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'promoteUser' (returns error code or SOAP_OK)
	virtual	int promoteUser(LONG64 cookie, char *localUser, char *globalUser, char *loginname, int &result) { return this->promoteUser(NULL, NULL, cookie, localUser, globalUser, loginname, result); }
	virtual	int promoteUser(const char *endpoint, const char *soap_action, LONG64 cookie, char *localUser, char *globalUser, char *loginname, int &result);

	/// Web service operation 'addGlobalUser' (returns error code or SOAP_OK)
	virtual	int addGlobalUser(LONG64 cookie, ns1__CGlobalUser *pUser, int &result) { return this->addGlobalUser(NULL, NULL, cookie, pUser, result); }
	virtual	int addGlobalUser(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CGlobalUser *pUser, int &result);

	/// Web service operation 'getCustomer' (returns error code or SOAP_OK)
	virtual	int getCustomer(LONG64 cookie, char *firstName, char *middleInitials, char *lastName, struct ns1__getCustomerResponse &_param_41) { return this->getCustomer(NULL, NULL, cookie, firstName, middleInitials, lastName, _param_41); }
	virtual	int getCustomer(const char *endpoint, const char *soap_action, LONG64 cookie, char *firstName, char *middleInitials, char *lastName, struct ns1__getCustomerResponse &_param_41);

	/// Web service operation 'getCustomerByRecordID' (returns error code or SOAP_OK)
	virtual	int getCustomerByRecordID(LONG64 cookie, LONG64 recordID, struct ns1__getCustomerByRecordIDResponse &_param_42) { return this->getCustomerByRecordID(NULL, NULL, cookie, recordID, _param_42); }
	virtual	int getCustomerByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, struct ns1__getCustomerByRecordIDResponse &_param_42);

	/// Web service operation 'addCustomer' (returns error code or SOAP_OK)
	virtual	int addCustomer(LONG64 cookie, ns1__CUser *pCustomer, LONG64 &recordID) { return this->addCustomer(NULL, NULL, cookie, pCustomer, recordID); }
	virtual	int addCustomer(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CUser *pCustomer, LONG64 &recordID);

	/// Web service operation 'editCustomer' (returns error code or SOAP_OK)
	virtual	int editCustomer(LONG64 cookie, char *firstName, char *middleInitials, char *lastName, struct ns1__editCustomerResponse &_param_43) { return this->editCustomer(NULL, NULL, cookie, firstName, middleInitials, lastName, _param_43); }
	virtual	int editCustomer(const char *endpoint, const char *soap_action, LONG64 cookie, char *firstName, char *middleInitials, char *lastName, struct ns1__editCustomerResponse &_param_43);

	/// Web service operation 'editCustomerByRecordID' (returns error code or SOAP_OK)
	virtual	int editCustomerByRecordID(LONG64 cookie, LONG64 recordID, struct ns1__editCustomerByRecordIDResponse &_param_44) { return this->editCustomerByRecordID(NULL, NULL, cookie, recordID, _param_44); }
	virtual	int editCustomerByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, struct ns1__editCustomerByRecordIDResponse &_param_44);

	/// Web service operation 'saveCustomer' (returns error code or SOAP_OK)
	virtual	int saveCustomer(LONG64 cookie, char *firstName, char *middleInitials, char *lastName, ns1__CUser *pCustomer, int &result) { return this->saveCustomer(NULL, NULL, cookie, firstName, middleInitials, lastName, pCustomer, result); }
	virtual	int saveCustomer(const char *endpoint, const char *soap_action, LONG64 cookie, char *firstName, char *middleInitials, char *lastName, ns1__CUser *pCustomer, int &result);

	/// Web service operation 'deleteCustomer' (returns error code or SOAP_OK)
	virtual	int deleteCustomer(LONG64 cookie, char *firstName, char *middleInitials, char *lastName, int &result) { return this->deleteCustomer(NULL, NULL, cookie, firstName, middleInitials, lastName, result); }
	virtual	int deleteCustomer(const char *endpoint, const char *soap_action, LONG64 cookie, char *firstName, char *middleInitials, char *lastName, int &result);

	/// Web service operation 'deleteCustomerByRecordID' (returns error code or SOAP_OK)
	virtual	int deleteCustomerByRecordID(LONG64 cookie, LONG64 recordID, int &result) { return this->deleteCustomerByRecordID(NULL, NULL, cookie, recordID, result); }
	virtual	int deleteCustomerByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'cancelSaveCustomer' (returns error code or SOAP_OK)
	virtual	int cancelSaveCustomer(LONG64 cookie, LONG64 recordID, int &result) { return this->cancelSaveCustomer(NULL, NULL, cookie, recordID, result); }
	virtual	int cancelSaveCustomer(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'promoteCustomer' (returns error code or SOAP_OK)
	virtual	int promoteCustomer(LONG64 cookie, char *localCustomer, char *globalUser, char *loginname, int &result) { return this->promoteCustomer(NULL, NULL, cookie, localCustomer, globalUser, loginname, result); }
	virtual	int promoteCustomer(const char *endpoint, const char *soap_action, LONG64 cookie, char *localCustomer, char *globalUser, char *loginname, int &result);

	/// Web service operation 'addGlobalCustomer' (returns error code or SOAP_OK)
	virtual	int addGlobalCustomer(LONG64 cookie, ns1__CGlobalUser *pUser, int &result) { return this->addGlobalCustomer(NULL, NULL, cookie, pUser, result); }
	virtual	int addGlobalCustomer(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CGlobalUser *pUser, int &result);

	/// Web service operation 'getLinksForItem' (returns error code or SOAP_OK)
	virtual	int getLinksForItem(LONG64 cookie, char *tablename, LONG64 itemRecordID, struct ns1__getLinksForItemResponse &_param_45) { return this->getLinksForItem(NULL, NULL, cookie, tablename, itemRecordID, _param_45); }
	virtual	int getLinksForItem(const char *endpoint, const char *soap_action, LONG64 cookie, char *tablename, LONG64 itemRecordID, struct ns1__getLinksForItemResponse &_param_45);

	/// Web service operation 'getLinksForDefect' (returns error code or SOAP_OK)
	virtual	int getLinksForDefect(LONG64 cookie, LONG64 defectRecordID, struct ns1__getLinksForDefectResponse &_param_46) { return this->getLinksForDefect(NULL, NULL, cookie, defectRecordID, _param_46); }
	virtual	int getLinksForDefect(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 defectRecordID, struct ns1__getLinksForDefectResponse &_param_46);

	/// Web service operation 'getLink' (returns error code or SOAP_OK)
	virtual	int getLink(LONG64 cookie, LONG64 linkID, struct ns1__getLinkResponse &_param_47) { return this->getLink(NULL, NULL, cookie, linkID, _param_47); }
	virtual	int getLink(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 linkID, struct ns1__getLinkResponse &_param_47);

	/// Web service operation 'addLink' (returns error code or SOAP_OK)
	virtual	int addLink(LONG64 cookie, ns1__CLink *pLink, LONG64 &recordID) { return this->addLink(NULL, NULL, cookie, pLink, recordID); }
	virtual	int addLink(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CLink *pLink, LONG64 &recordID);

	/// Web service operation 'deleteLink' (returns error code or SOAP_OK)
	virtual	int deleteLink(LONG64 cookie, LONG64 linkID, int &result) { return this->deleteLink(NULL, NULL, cookie, linkID, result); }
	virtual	int deleteLink(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 linkID, int &result);

	/// Web service operation 'editLink' (returns error code or SOAP_OK)
	virtual	int editLink(LONG64 cookie, LONG64 linkID, struct ns1__editLinkResponse &_param_48) { return this->editLink(NULL, NULL, cookie, linkID, _param_48); }
	virtual	int editLink(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 linkID, struct ns1__editLinkResponse &_param_48);

	/// Web service operation 'saveLink' (returns error code or SOAP_OK)
	virtual	int saveLink(LONG64 cookie, ns1__CLink *pLink, int &result) { return this->saveLink(NULL, NULL, cookie, pLink, result); }
	virtual	int saveLink(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CLink *pLink, int &result);

	/// Web service operation 'cancelSaveLink' (returns error code or SOAP_OK)
	virtual	int cancelSaveLink(LONG64 cookie, LONG64 linkID, int &result) { return this->cancelSaveLink(NULL, NULL, cookie, linkID, result); }
	virtual	int cancelSaveLink(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 linkID, int &result);

	/// Web service operation 'getTestVariantTypes' (returns error code or SOAP_OK)
	virtual	int getTestVariantTypes(LONG64 cookie, struct ns1__getTestVariantTypesResponse &_param_49) { return this->getTestVariantTypes(NULL, NULL, cookie, _param_49); }
	virtual	int getTestVariantTypes(const char *endpoint, const char *soap_action, LONG64 cookie, struct ns1__getTestVariantTypesResponse &_param_49);

	/// Web service operation 'getTestRunStepsModes' (returns error code or SOAP_OK)
	virtual	int getTestRunStepsModes(LONG64 cookie, struct ns1__getTestRunStepsModesResponse &_param_50) { return this->getTestRunStepsModes(NULL, NULL, cookie, _param_50); }
	virtual	int getTestRunStepsModes(const char *endpoint, const char *soap_action, LONG64 cookie, struct ns1__getTestRunStepsModesResponse &_param_50);

	/// Web service operation 'getTestCase' (returns error code or SOAP_OK)
	virtual	int getTestCase(LONG64 cookie, LONG64 testCaseNumber, char *summary, bool bDownloadAttachments, struct ns1__getTestCaseResponse &_param_51) { return this->getTestCase(NULL, NULL, cookie, testCaseNumber, summary, bDownloadAttachments, _param_51); }
	virtual	int getTestCase(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 testCaseNumber, char *summary, bool bDownloadAttachments, struct ns1__getTestCaseResponse &_param_51);

	/// Web service operation 'getTestCaseByRecordID' (returns error code or SOAP_OK)
	virtual	int getTestCaseByRecordID(LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__getTestCaseByRecordIDResponse &_param_52) { return this->getTestCaseByRecordID(NULL, NULL, cookie, recordID, bDownloadAttachments, _param_52); }
	virtual	int getTestCaseByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__getTestCaseByRecordIDResponse &_param_52);

	/// Web service operation 'addTestCase' (returns error code or SOAP_OK)
	virtual	int addTestCase(LONG64 cookie, ns1__CTestCase *pTestCase, LONG64 &recordID) { return this->addTestCase(NULL, NULL, cookie, pTestCase, recordID); }
	virtual	int addTestCase(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CTestCase *pTestCase, LONG64 &recordID);

	/// Web service operation 'deleteTestCase' (returns error code or SOAP_OK)
	virtual	int deleteTestCase(LONG64 cookie, LONG64 testCaseNumber, char *summary, bool bDeleteAssociatedTestRuns, int &result) { return this->deleteTestCase(NULL, NULL, cookie, testCaseNumber, summary, bDeleteAssociatedTestRuns, result); }
	virtual	int deleteTestCase(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 testCaseNumber, char *summary, bool bDeleteAssociatedTestRuns, int &result);

	/// Web service operation 'deleteTestCaseByRecordID' (returns error code or SOAP_OK)
	virtual	int deleteTestCaseByRecordID(LONG64 cookie, LONG64 recordID, bool bDeleteAssociatedTestRun, int &result) { return this->deleteTestCaseByRecordID(NULL, NULL, cookie, recordID, bDeleteAssociatedTestRun, result); }
	virtual	int deleteTestCaseByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool bDeleteAssociatedTestRun, int &result);

	/// Web service operation 'editTestCase' (returns error code or SOAP_OK)
	virtual	int editTestCase(LONG64 cookie, LONG64 testCaseNumber, char *summary, bool bDownloadAttachments, struct ns1__editTestCaseResponse &_param_53) { return this->editTestCase(NULL, NULL, cookie, testCaseNumber, summary, bDownloadAttachments, _param_53); }
	virtual	int editTestCase(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 testCaseNumber, char *summary, bool bDownloadAttachments, struct ns1__editTestCaseResponse &_param_53);

	/// Web service operation 'editTestCaseByRecordID' (returns error code or SOAP_OK)
	virtual	int editTestCaseByRecordID(LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__editTestCaseByRecordIDResponse &_param_54) { return this->editTestCaseByRecordID(NULL, NULL, cookie, recordID, bDownloadAttachments, _param_54); }
	virtual	int editTestCaseByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__editTestCaseByRecordIDResponse &_param_54);

	/// Web service operation 'saveTestCase' (returns error code or SOAP_OK)
	virtual	int saveTestCase(LONG64 cookie, ns1__CTestCase *pTestCase, int &result) { return this->saveTestCase(NULL, NULL, cookie, pTestCase, result); }
	virtual	int saveTestCase(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CTestCase *pTestCase, int &result);

	/// Web service operation 'cancelSaveTestCase' (returns error code or SOAP_OK)
	virtual	int cancelSaveTestCase(LONG64 cookie, LONG64 recordID, int &result) { return this->cancelSaveTestCase(NULL, NULL, cookie, recordID, result); }
	virtual	int cancelSaveTestCase(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'getTestRun' (returns error code or SOAP_OK)
	virtual	int getTestRun(LONG64 cookie, LONG64 testRunNumber, char *summary, bool bDownloadAttachments, struct ns1__getTestRunResponse &_param_55) { return this->getTestRun(NULL, NULL, cookie, testRunNumber, summary, bDownloadAttachments, _param_55); }
	virtual	int getTestRun(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 testRunNumber, char *summary, bool bDownloadAttachments, struct ns1__getTestRunResponse &_param_55);

	/// Web service operation 'getTestRunByRecordID' (returns error code or SOAP_OK)
	virtual	int getTestRunByRecordID(LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__getTestRunByRecordIDResponse &_param_56) { return this->getTestRunByRecordID(NULL, NULL, cookie, recordID, bDownloadAttachments, _param_56); }
	virtual	int getTestRunByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__getTestRunByRecordIDResponse &_param_56);

	/// Web service operation 'deleteTestRun' (returns error code or SOAP_OK)
	virtual	int deleteTestRun(LONG64 cookie, LONG64 testRunNumber, char *summary, int &result) { return this->deleteTestRun(NULL, NULL, cookie, testRunNumber, summary, result); }
	virtual	int deleteTestRun(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 testRunNumber, char *summary, int &result);

	/// Web service operation 'deleteTestRunByRecordID' (returns error code or SOAP_OK)
	virtual	int deleteTestRunByRecordID(LONG64 cookie, LONG64 recordID, int &result) { return this->deleteTestRunByRecordID(NULL, NULL, cookie, recordID, result); }
	virtual	int deleteTestRunByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'editTestRun' (returns error code or SOAP_OK)
	virtual	int editTestRun(LONG64 cookie, LONG64 testRunNumber, char *summary, bool bDownloadAttachments, struct ns1__editTestRunResponse &_param_57) { return this->editTestRun(NULL, NULL, cookie, testRunNumber, summary, bDownloadAttachments, _param_57); }
	virtual	int editTestRun(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 testRunNumber, char *summary, bool bDownloadAttachments, struct ns1__editTestRunResponse &_param_57);

	/// Web service operation 'editTestRunByRecordID' (returns error code or SOAP_OK)
	virtual	int editTestRunByRecordID(LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__editTestRunByRecordIDResponse &_param_58) { return this->editTestRunByRecordID(NULL, NULL, cookie, recordID, bDownloadAttachments, _param_58); }
	virtual	int editTestRunByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__editTestRunByRecordIDResponse &_param_58);

	/// Web service operation 'saveTestRun' (returns error code or SOAP_OK)
	virtual	int saveTestRun(LONG64 cookie, ns1__CTestRun *pTestRun, int &result) { return this->saveTestRun(NULL, NULL, cookie, pTestRun, result); }
	virtual	int saveTestRun(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CTestRun *pTestRun, int &result);

	/// Web service operation 'cancelSaveTestRun' (returns error code or SOAP_OK)
	virtual	int cancelSaveTestRun(LONG64 cookie, LONG64 recordID, int &result) { return this->cancelSaveTestRun(NULL, NULL, cookie, recordID, result); }
	virtual	int cancelSaveTestRun(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'createDefectForTestRun' (returns error code or SOAP_OK)
	virtual	int createDefectForTestRun(LONG64 cookie, LONG64 recordID, struct ns1__createDefectForTestRunResponse &_param_59) { return this->createDefectForTestRun(NULL, NULL, cookie, recordID, _param_59); }
	virtual	int createDefectForTestRun(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, struct ns1__createDefectForTestRunResponse &_param_59);

	/// Web service operation 'generateTestRuns' (returns error code or SOAP_OK)
	virtual	int generateTestRuns(LONG64 cookie, LONG64 recordID, ArrayOfCTestRunVariantField *testVariants, char *testRunSet, struct ns1__generateTestRunsResponse &_param_60) { return this->generateTestRuns(NULL, NULL, cookie, recordID, testVariants, testRunSet, _param_60); }
	virtual	int generateTestRuns(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, ArrayOfCTestRunVariantField *testVariants, char *testRunSet, struct ns1__generateTestRunsResponse &_param_60);

	/// Web service operation 'getFolderTypeByName' (returns error code or SOAP_OK)
	virtual	int getFolderTypeByName(LONG64 cookie, char *name, struct ns1__getFolderTypeByNameResponse &_param_61) { return this->getFolderTypeByName(NULL, NULL, cookie, name, _param_61); }
	virtual	int getFolderTypeByName(const char *endpoint, const char *soap_action, LONG64 cookie, char *name, struct ns1__getFolderTypeByNameResponse &_param_61);

	/// Web service operation 'getFolderTypeList' (returns error code or SOAP_OK)
	virtual	int getFolderTypeList(LONG64 cookie, struct ns1__getFolderTypeListResponse &_param_62) { return this->getFolderTypeList(NULL, NULL, cookie, _param_62); }
	virtual	int getFolderTypeList(const char *endpoint, const char *soap_action, LONG64 cookie, struct ns1__getFolderTypeListResponse &_param_62);

	/// Web service operation 'addFolder' (returns error code or SOAP_OK)
	virtual	int addFolder(LONG64 cookie, ns1__CFolder *pFolder, LONG64 &recordID) { return this->addFolder(NULL, NULL, cookie, pFolder, recordID); }
	virtual	int addFolder(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CFolder *pFolder, LONG64 &recordID);

	/// Web service operation 'editFolder' (returns error code or SOAP_OK)
	virtual	int editFolder(LONG64 cookie, char *folderPath, struct ns1__editFolderResponse &_param_63) { return this->editFolder(NULL, NULL, cookie, folderPath, _param_63); }
	virtual	int editFolder(const char *endpoint, const char *soap_action, LONG64 cookie, char *folderPath, struct ns1__editFolderResponse &_param_63);

	/// Web service operation 'editFolderByRecordID' (returns error code or SOAP_OK)
	virtual	int editFolderByRecordID(LONG64 cookie, LONG64 recordID, bool publicFolder, struct ns1__editFolderByRecordIDResponse &_param_64) { return this->editFolderByRecordID(NULL, NULL, cookie, recordID, publicFolder, _param_64); }
	virtual	int editFolderByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool publicFolder, struct ns1__editFolderByRecordIDResponse &_param_64);

	/// Web service operation 'saveFolder' (returns error code or SOAP_OK)
	virtual	int saveFolder(LONG64 cookie, ns1__CFolder *pFolder, int &result) { return this->saveFolder(NULL, NULL, cookie, pFolder, result); }
	virtual	int saveFolder(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CFolder *pFolder, int &result);

	/// Web service operation 'cancelSaveFolder' (returns error code or SOAP_OK)
	virtual	int cancelSaveFolder(LONG64 cookie, LONG64 recordID, int &result) { return this->cancelSaveFolder(NULL, NULL, cookie, recordID, result); }
	virtual	int cancelSaveFolder(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'getFolder' (returns error code or SOAP_OK)
	virtual	int getFolder(LONG64 cookie, char *path, struct ns1__getFolderResponse &_param_65) { return this->getFolder(NULL, NULL, cookie, path, _param_65); }
	virtual	int getFolder(const char *endpoint, const char *soap_action, LONG64 cookie, char *path, struct ns1__getFolderResponse &_param_65);

	/// Web service operation 'getFolderByRecordID' (returns error code or SOAP_OK)
	virtual	int getFolderByRecordID(LONG64 cookie, LONG64 recordID, bool publicFolder, struct ns1__getFolderByRecordIDResponse &_param_66) { return this->getFolderByRecordID(NULL, NULL, cookie, recordID, publicFolder, _param_66); }
	virtual	int getFolderByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool publicFolder, struct ns1__getFolderByRecordIDResponse &_param_66);

	/// Web service operation 'deleteFolder' (returns error code or SOAP_OK)
	virtual	int deleteFolder(LONG64 cookie, char *folderPath, int &result) { return this->deleteFolder(NULL, NULL, cookie, folderPath, result); }
	virtual	int deleteFolder(const char *endpoint, const char *soap_action, LONG64 cookie, char *folderPath, int &result);

	/// Web service operation 'deleteFolderByRecordID' (returns error code or SOAP_OK)
	virtual	int deleteFolderByRecordID(LONG64 cookie, LONG64 recordID, bool publicFolder, int &result) { return this->deleteFolderByRecordID(NULL, NULL, cookie, recordID, publicFolder, result); }
	virtual	int deleteFolderByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool publicFolder, int &result);

	/// Web service operation 'addEntityToFolderByRecordID' (returns error code or SOAP_OK)
	virtual	int addEntityToFolderByRecordID(LONG64 cookie, LONG64 recordID, bool publicFolder, LONG64 entityRecordID, char *entityTableName, int &itemRecordID) { return this->addEntityToFolderByRecordID(NULL, NULL, cookie, recordID, publicFolder, entityRecordID, entityTableName, itemRecordID); }
	virtual	int addEntityToFolderByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool publicFolder, LONG64 entityRecordID, char *entityTableName, int &itemRecordID);

	/// Web service operation 'removeEntityFromFolderByRecordID' (returns error code or SOAP_OK)
	virtual	int removeEntityFromFolderByRecordID(LONG64 cookie, LONG64 recordID, bool publicFolder, ns1__CFolderItem *entity, int &result) { return this->removeEntityFromFolderByRecordID(NULL, NULL, cookie, recordID, publicFolder, entity, result); }
	virtual	int removeEntityFromFolderByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool publicFolder, ns1__CFolderItem *entity, int &result);

	/// Web service operation 'getEntityListForFolderByRecordID' (returns error code or SOAP_OK)
	virtual	int getEntityListForFolderByRecordID(LONG64 cookie, LONG64 recordID, bool publicFolder, struct ns1__getEntityListForFolderByRecordIDResponse &_param_67) { return this->getEntityListForFolderByRecordID(NULL, NULL, cookie, recordID, publicFolder, _param_67); }
	virtual	int getEntityListForFolderByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool publicFolder, struct ns1__getEntityListForFolderByRecordIDResponse &_param_67);

	/// Web service operation 'getFolderListForEntityByRecordID' (returns error code or SOAP_OK)
	virtual	int getFolderListForEntityByRecordID(LONG64 cookie, char *tablename, LONG64 recordID, struct ns1__getFolderListForEntityByRecordIDResponse &_param_68) { return this->getFolderListForEntityByRecordID(NULL, NULL, cookie, tablename, recordID, _param_68); }
	virtual	int getFolderListForEntityByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, char *tablename, LONG64 recordID, struct ns1__getFolderListForEntityByRecordIDResponse &_param_68);

	/// Web service operation 'getFolderPathSeparator' (returns error code or SOAP_OK)
	virtual	int getFolderPathSeparator(LONG64 cookie, char &separator) { return this->getFolderPathSeparator(NULL, NULL, cookie, separator); }
	virtual	int getFolderPathSeparator(const char *endpoint, const char *soap_action, LONG64 cookie, char &separator);

	/// Web service operation 'getRootPublicFolderPath' (returns error code or SOAP_OK)
	virtual	int getRootPublicFolderPath(LONG64 cookie, char *&strPublicPath) { return this->getRootPublicFolderPath(NULL, NULL, cookie, strPublicPath); }
	virtual	int getRootPublicFolderPath(const char *endpoint, const char *soap_action, LONG64 cookie, char *&strPublicPath);

	/// Web service operation 'getRootPrivateFolderPath' (returns error code or SOAP_OK)
	virtual	int getRootPrivateFolderPath(LONG64 cookie, char *&strPrivatePath) { return this->getRootPrivateFolderPath(NULL, NULL, cookie, strPrivatePath); }
	virtual	int getRootPrivateFolderPath(const char *endpoint, const char *soap_action, LONG64 cookie, char *&strPrivatePath);

	/// Web service operation 'editFolderItemRank' (returns error code or SOAP_OK)
	virtual	int editFolderItemRank(LONG64 cookie, LONG64 recordID, bool publicFolder, struct ns1__editFolderItemRankResponse &_param_69) { return this->editFolderItemRank(NULL, NULL, cookie, recordID, publicFolder, _param_69); }
	virtual	int editFolderItemRank(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool publicFolder, struct ns1__editFolderItemRankResponse &_param_69);

	/// Web service operation 'saveFolderItemRank' (returns error code or SOAP_OK)
	virtual	int saveFolderItemRank(LONG64 cookie, LONG64 recordID, bool publicFolder, ArrayOfCFolderItem *folderItemList, int &result) { return this->saveFolderItemRank(NULL, NULL, cookie, recordID, publicFolder, folderItemList, result); }
	virtual	int saveFolderItemRank(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool publicFolder, ArrayOfCFolderItem *folderItemList, int &result);

	/// Web service operation 'cancelSaveFolderItemRank' (returns error code or SOAP_OK)
	virtual	int cancelSaveFolderItemRank(LONG64 cookie, LONG64 recordID, int &result) { return this->cancelSaveFolderItemRank(NULL, NULL, cookie, recordID, result); }
	virtual	int cancelSaveFolderItemRank(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'getRequirement' (returns error code or SOAP_OK)
	virtual	int getRequirement(LONG64 cookie, LONG64 requirementNumber, char *summary, bool bDownloadAttachments, struct ns1__getRequirementResponse &_param_70) { return this->getRequirement(NULL, NULL, cookie, requirementNumber, summary, bDownloadAttachments, _param_70); }
	virtual	int getRequirement(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 requirementNumber, char *summary, bool bDownloadAttachments, struct ns1__getRequirementResponse &_param_70);

	/// Web service operation 'getRequirementByRecordID' (returns error code or SOAP_OK)
	virtual	int getRequirementByRecordID(LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__getRequirementByRecordIDResponse &_param_71) { return this->getRequirementByRecordID(NULL, NULL, cookie, recordID, bDownloadAttachments, _param_71); }
	virtual	int getRequirementByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__getRequirementByRecordIDResponse &_param_71);

	/// Web service operation 'addRequirement' (returns error code or SOAP_OK)
	virtual	int addRequirement(LONG64 cookie, ns1__CRequirement *pRequirement, LONG64 &recordID) { return this->addRequirement(NULL, NULL, cookie, pRequirement, recordID); }
	virtual	int addRequirement(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CRequirement *pRequirement, LONG64 &recordID);

	/// Web service operation 'deleteRequirement' (returns error code or SOAP_OK)
	virtual	int deleteRequirement(LONG64 cookie, LONG64 requirementNumber, char *summary, int &result) { return this->deleteRequirement(NULL, NULL, cookie, requirementNumber, summary, result); }
	virtual	int deleteRequirement(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 requirementNumber, char *summary, int &result);

	/// Web service operation 'deleteRequirementByRecordID' (returns error code or SOAP_OK)
	virtual	int deleteRequirementByRecordID(LONG64 cookie, LONG64 recordID, int &result) { return this->deleteRequirementByRecordID(NULL, NULL, cookie, recordID, result); }
	virtual	int deleteRequirementByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'editRequirement' (returns error code or SOAP_OK)
	virtual	int editRequirement(LONG64 cookie, LONG64 requirementNumber, char *summary, bool bDownloadAttachments, struct ns1__editRequirementResponse &_param_72) { return this->editRequirement(NULL, NULL, cookie, requirementNumber, summary, bDownloadAttachments, _param_72); }
	virtual	int editRequirement(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 requirementNumber, char *summary, bool bDownloadAttachments, struct ns1__editRequirementResponse &_param_72);

	/// Web service operation 'editRequirementByRecordID' (returns error code or SOAP_OK)
	virtual	int editRequirementByRecordID(LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__editRequirementByRecordIDResponse &_param_73) { return this->editRequirementByRecordID(NULL, NULL, cookie, recordID, bDownloadAttachments, _param_73); }
	virtual	int editRequirementByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__editRequirementByRecordIDResponse &_param_73);

	/// Web service operation 'saveRequirement' (returns error code or SOAP_OK)
	virtual	int saveRequirement(LONG64 cookie, ns1__CRequirement *pRequirement, int &result) { return this->saveRequirement(NULL, NULL, cookie, pRequirement, result); }
	virtual	int saveRequirement(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CRequirement *pRequirement, int &result);

	/// Web service operation 'cancelSaveRequirement' (returns error code or SOAP_OK)
	virtual	int cancelSaveRequirement(LONG64 cookie, LONG64 recordID, int &result) { return this->cancelSaveRequirement(NULL, NULL, cookie, recordID, result); }
	virtual	int cancelSaveRequirement(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'appendToRequirementDocument' (returns error code or SOAP_OK)
	virtual	int appendToRequirementDocument(LONG64 cookie, LONG64 requirementID, LONG64 documentID, LONG64 parentRequirementID, int &result) { return this->appendToRequirementDocument(NULL, NULL, cookie, requirementID, documentID, parentRequirementID, result); }
	virtual	int appendToRequirementDocument(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 requirementID, LONG64 documentID, LONG64 parentRequirementID, int &result);

	/// Web service operation 'getDocumentIDsForRequirement' (returns error code or SOAP_OK)
	virtual	int getDocumentIDsForRequirement(LONG64 cookie, LONG64 requirementID, struct ns1__getDocumentIDsForRequirementResponse &_param_74) { return this->getDocumentIDsForRequirement(NULL, NULL, cookie, requirementID, _param_74); }
	virtual	int getDocumentIDsForRequirement(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 requirementID, struct ns1__getDocumentIDsForRequirementResponse &_param_74);

	/// Web service operation 'changeRequirementType' (returns error code or SOAP_OK)
	virtual	int changeRequirementType(LONG64 cookie, LONG64 requirementID, char *newTypeName, int &result) { return this->changeRequirementType(NULL, NULL, cookie, requirementID, newTypeName, result); }
	virtual	int changeRequirementType(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 requirementID, char *newTypeName, int &result);

	/// Web service operation 'getRequirementDocument' (returns error code or SOAP_OK)
	virtual	int getRequirementDocument(LONG64 cookie, LONG64 documentNumber, char *name, bool bDownloadAttachments, struct ns1__getRequirementDocumentResponse &_param_75) { return this->getRequirementDocument(NULL, NULL, cookie, documentNumber, name, bDownloadAttachments, _param_75); }
	virtual	int getRequirementDocument(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 documentNumber, char *name, bool bDownloadAttachments, struct ns1__getRequirementDocumentResponse &_param_75);

	/// Web service operation 'getRequirementDocumentByRecordID' (returns error code or SOAP_OK)
	virtual	int getRequirementDocumentByRecordID(LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__getRequirementDocumentByRecordIDResponse &_param_76) { return this->getRequirementDocumentByRecordID(NULL, NULL, cookie, recordID, bDownloadAttachments, _param_76); }
	virtual	int getRequirementDocumentByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__getRequirementDocumentByRecordIDResponse &_param_76);

	/// Web service operation 'addRequirementDocument' (returns error code or SOAP_OK)
	virtual	int addRequirementDocument(LONG64 cookie, ns1__CRequirementDocument *pRequirementDocument, LONG64 &recordID) { return this->addRequirementDocument(NULL, NULL, cookie, pRequirementDocument, recordID); }
	virtual	int addRequirementDocument(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CRequirementDocument *pRequirementDocument, LONG64 &recordID);

	/// Web service operation 'deleteRequirementDocument' (returns error code or SOAP_OK)
	virtual	int deleteRequirementDocument(LONG64 cookie, LONG64 documentNumber, char *name, bool bDeleteAssociatedRequirements, int &result) { return this->deleteRequirementDocument(NULL, NULL, cookie, documentNumber, name, bDeleteAssociatedRequirements, result); }
	virtual	int deleteRequirementDocument(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 documentNumber, char *name, bool bDeleteAssociatedRequirements, int &result);

	/// Web service operation 'deleteRequirementDocumentByRecordID' (returns error code or SOAP_OK)
	virtual	int deleteRequirementDocumentByRecordID(LONG64 cookie, LONG64 recordID, bool bDeleteAssociatedRequirements, int &result) { return this->deleteRequirementDocumentByRecordID(NULL, NULL, cookie, recordID, bDeleteAssociatedRequirements, result); }
	virtual	int deleteRequirementDocumentByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool bDeleteAssociatedRequirements, int &result);

	/// Web service operation 'editRequirementDocument' (returns error code or SOAP_OK)
	virtual	int editRequirementDocument(LONG64 cookie, LONG64 documentNumber, char *name, bool bDownloadAttachments, struct ns1__editRequirementDocumentResponse &_param_77) { return this->editRequirementDocument(NULL, NULL, cookie, documentNumber, name, bDownloadAttachments, _param_77); }
	virtual	int editRequirementDocument(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 documentNumber, char *name, bool bDownloadAttachments, struct ns1__editRequirementDocumentResponse &_param_77);

	/// Web service operation 'editRequirementDocumentByRecordID' (returns error code or SOAP_OK)
	virtual	int editRequirementDocumentByRecordID(LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__editRequirementDocumentByRecordIDResponse &_param_78) { return this->editRequirementDocumentByRecordID(NULL, NULL, cookie, recordID, bDownloadAttachments, _param_78); }
	virtual	int editRequirementDocumentByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, bool bDownloadAttachments, struct ns1__editRequirementDocumentByRecordIDResponse &_param_78);

	/// Web service operation 'saveRequirementDocument' (returns error code or SOAP_OK)
	virtual	int saveRequirementDocument(LONG64 cookie, ns1__CRequirementDocument *pRequirementDocument, int &result) { return this->saveRequirementDocument(NULL, NULL, cookie, pRequirementDocument, result); }
	virtual	int saveRequirementDocument(const char *endpoint, const char *soap_action, LONG64 cookie, ns1__CRequirementDocument *pRequirementDocument, int &result);

	/// Web service operation 'cancelSaveRequirementDocument' (returns error code or SOAP_OK)
	virtual	int cancelSaveRequirementDocument(LONG64 cookie, LONG64 recordID, int &result) { return this->cancelSaveRequirementDocument(NULL, NULL, cookie, recordID, result); }
	virtual	int cancelSaveRequirementDocument(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 recordID, int &result);

	/// Web service operation 'createSnapshot' (returns error code or SOAP_OK)
	virtual	int createSnapshot(LONG64 cookie, LONG64 documentID, ns1__CSnapshotInfo *snapshot, int &result) { return this->createSnapshot(NULL, NULL, cookie, documentID, snapshot, result); }
	virtual	int createSnapshot(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 documentID, ns1__CSnapshotInfo *snapshot, int &result);

	/// Web service operation 'getRequirementIDsForDocument' (returns error code or SOAP_OK)
	virtual	int getRequirementIDsForDocument(LONG64 cookie, LONG64 documentID, struct ns1__getRequirementIDsForDocumentResponse &_param_79) { return this->getRequirementIDsForDocument(NULL, NULL, cookie, documentID, _param_79); }
	virtual	int getRequirementIDsForDocument(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 documentID, struct ns1__getRequirementIDsForDocumentResponse &_param_79);

	/// Web service operation 'getDocumentTree' (returns error code or SOAP_OK)
	virtual	int getDocumentTree(LONG64 cookie, LONG64 documentID, struct ns1__getDocumentTreeResponse &_param_80) { return this->getDocumentTree(NULL, NULL, cookie, documentID, _param_80); }
	virtual	int getDocumentTree(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 documentID, struct ns1__getDocumentTreeResponse &_param_80);

	/// Web service operation 'getFolderTreeByRecordID' (returns error code or SOAP_OK)
	virtual	int getFolderTreeByRecordID(LONG64 cookie, LONG64 treeRootFolderID, struct ns1__getFolderTreeByRecordIDResponse &_param_81) { return this->getFolderTreeByRecordID(NULL, NULL, cookie, treeRootFolderID, _param_81); }
	virtual	int getFolderTreeByRecordID(const char *endpoint, const char *soap_action, LONG64 cookie, LONG64 treeRootFolderID, struct ns1__getFolderTreeByRecordIDResponse &_param_81);

	/// Web service operation 'getFolderTree' (returns error code or SOAP_OK)
	virtual	int getFolderTree(LONG64 cookie, char *treeRootFolderPath, struct ns1__getFolderTreeResponse &_param_82) { return this->getFolderTree(NULL, NULL, cookie, treeRootFolderPath, _param_82); }
	virtual	int getFolderTree(const char *endpoint, const char *soap_action, LONG64 cookie, char *treeRootFolderPath, struct ns1__getFolderTreeResponse &_param_82);

	/// Web service operation 'getItemHyperlinks' (returns error code or SOAP_OK)
	virtual	int getItemHyperlinks(LONG64 cookie, char *itemType, LONG64 itemID, struct ns1__getItemHyperlinksResponse &_param_83) { return this->getItemHyperlinks(NULL, NULL, cookie, itemType, itemID, _param_83); }
	virtual	int getItemHyperlinks(const char *endpoint, const char *soap_action, LONG64 cookie, char *itemType, LONG64 itemID, struct ns1__getItemHyperlinksResponse &_param_83);
};
#endif
