#pragma once

// Version history and change log
#define RE_FILE_SYSTEM_VERSION_INITIAL_RELEASE										"001"
#define RE_FILE_SYSTEM_VERSION_MOBU_BONE_SCALE_EXTEND								"002"
#define RE_FILE_SYSTEM_VERSION_EXPORT_REMOVE_VERTEX_USER_DATA						"003"
#define RE_FILE_SYSTEM_VERSION_MAX_STABLE_MATERIAL_ID_EXPORT						"004"
#define RE_FILE_SYSTEM_VERSION_MOBU_SKIN_TOOLS_WORKING								"005"
#define RE_FILE_SYSTEM_VERSION_MOBU_EXPORTER_REFACTOR								"006"
#define RE_FILE_SYSTEM_VERSION_MOBU_EXPORT_CORRUPTED_DATA_BLOCK						"007"
#define RE_FILE_SYSTEM_VERSION_MOBU_EXPORT_BONES_COUNT_MISMATCH_WITH_RIGFILE		"008"
#define RE_FILE_SYSTEM_VERSION_MAX_PHYSICAL_MATERIAL_FIX							"009"
#define RE_FILE_SYSTEM_VERSION_MAX_EXPORT_VERTEX_COLOR_ALPHA_FIX					"010"
#define RE_FILE_SYSTEM_VERSION_MAX_EXPORT_VERTEX_COLOR_ALPHA_CRASH_FIX				"011"
#define RE_FILE_SYSTEM_VERSION_MAX_EXPORT_VERTEX_COLOR_ALPHA_REMOVE_HACK			"012"
#define RE_FILE_SYSTEM_VERSION_MAX_EXPORT_VERTEX_ALPHA_FACE_ID_FIX					"013"
#define RE_FILE_SYSTEM_VERSION_SPLIT_NODES_TO_FILES									"014"
#define RE_FILE_SYSTEM_VERSION_8_BONES_SKINNING_SUPPORT								"015"
#define RE_FILE_SYSTEM_VERSION_ADDED_NEW_SAVE_FUNCTIONS_FOR_FUTURE					"016"
#define RE_FILE_SYSTEM_VERSION_ROLLBACK_8_BONES_BECAUSE_OF_BROKEN_UV				"017"
#define RE_FILE_SYSTEM_VERSION_INTRODUCING_MACRO_USE_HDF5_HEADERS					"018"
#define RE_FILE_SYSTEM_VERSION_LEGACY_FACE_LOAD_FIX									"019"
#define RE_FILE_SYSTEM_VERSION_FIXED_MAYA_TESSELLATOR_DATA_GATHERING				"020"
#define RE_FILE_SYSTEM_VERSION_MATERIAL_GATHERING_FOR_MULTIPLE_OBJ_FIX				"021"
#define RE_FILE_SYSTEM_VERSION_FILE_LOADER_CHANGES									"022"
#define RE_FILE_SYSTEM_VERSION_FILE_LOADER_CHANGES_IN_FACEED_LIPS_VIEWER			"023"


// Current version
#define RE_FILE_SYSTEM_CURRENT_VERSION												RE_FILE_SYSTEM_VERSION_FILE_LOADER_CHANGES_IN_FACEED_LIPS_VIEWER
